blank_issues_enabled: true
#contact_links:
#  - name: Discord
#    url: https://discord.gg/mQ2RcJC
#    about: If you are having any minor issues or need help with the plugin, you can come ask us on our Discord server.
